- name: Install Base Packages
  hosts: Virtual_Machines
  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install sudo curl wget
      ansible.builtin.apt:
        pkg:
          - sudo
          - curl
          - wget

- name: Create Groups & Users
  hosts: Virtual_Machines
  tasks:
    - name: Create group hp-exploitation
      ansible.builtin.group:
        name: hb-exploitation
        gid: 12001
        system: true
    - name: Create user hb_exploit
      ansible.builtin.user:
        name: hb-exploit
        uid: 20001
        group: hb-exploitation
        groups: sudo, www-data
