- name: Install mariaDB and configure mariaDB Port
  hosts: VM1
  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install mariadb
      ansible.builtin.apt:
        name: mariadb-server

    - name: Build Sury deb
      command: bash -x /tmp/php.sh

    - name: Install php
      ansible.builtin.apt:
        pkg:
          - php8.1
          - libapache2-mod-php8.1

    - name: Restart apache2
      command: systemctl restart apache2

- name: Configure mariaDB port
  hosts: VM2
  tasks:
    - name: Create info.php
      command: echo "<?php phpinfo();" > /var/www/html/info.php
    
    - name: Create joomla dir
      command: mkdir /var/www/joomla